# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'allplayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!
  pod 'AFNetworking', '~> 4.0'
  pod 'Masonry'
  # Pods for allplayer

  target 'allplayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'allplayerUITests' do
    # Pods for testing
  end
  target 'AllPlayerSDK' do

  end
end
