# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



platform :ios,'9.0'
target 'playerSDK' do
    pod 'Masonry'
    
end

target 'PlayerDemo' do
    pod 'Masonry'
    pod 'AFNetworking'
    
end
